version: '3.5'

services:

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    image: server-app
    command: pnpm run dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    image: client-app
    command: pnpm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pharmtracker
    container_name: postgres
    ports:
      - '5432:5432'


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: questify-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
